name: Get the time from json

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "30 23 * * *"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Fetches repo
        uses: actions/checkout@v2
      - name: Generate time jsons
        run: |-
          curl http://worldtimeapi.org/api/timezone/America/Vancouver | jq . > time.json
      - name: Generate covid jsons
        run: |-
          curl https://health-infobase.canada.ca/src/data/covidLive/covid19.json | jq -r '.[] | select(.prname == "British Columbia")' | jq -s '.' > bc.json

      - name: Generate covid jsons
        run: |-
          curl https://health-infobase.canada.ca/src/data/covidLive/covid19.json | jq -r '.[] | select(.prname == "Canada")' | jq -s '.' > canada.json
      - name: Add results to config
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A *.json
          timestamp=$(date -u -Is)
          git commit -m "Update data on ${timestamp}" || exit 0
          git push

